name: publish

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/tifffile
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        python -m pip install build
    - name: Build package
      run: |
        python -m build --outdir dist/ .
    # - name: Install package
    #   run: python -m pip install dist/*.whl 'tifffile[test]'
    # - name: Run unit-tests
    #   run: |
    #     python -m pytest -vvra
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        print-hash: true
